<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Krita Canvas Rotation Tool</text>
        <Action name="MicroRotationADD">
            <icon></icon>
            <text>Micro Rotate Canvas +</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>Ctrl+6</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="MicroRotationSUB">
            <icon></icon>
            <text>Micro Rotate Canvas -</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>Ctrl+4</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="CoarseRotationADD">
            <icon></icon>
            <text>Coarse Rotation +</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>Alt+6</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="CoarseRotationSUB">
            <icon></icon>
            <text>Coarse Rotation -</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>Alt+4</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
